version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    container_name: django_container
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
